name: My Workflow
on:
  pull_request:
    types: [ opened ]
jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: perkexchange/github-action@v0.16-alpha
        name: Perk.Exchange Reward
        with:
            apiToken: ${{ secrets.PERKEXCHANGE_APITOKEN }}
            amount: 1
            currency: "USD"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}            
      - name: PR description replace
        uses: kaskar2008/action-pr-description-replace@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          find: '%DONATE_BUTTON%'
          replace: "[![Badge](https://perk.exchange/img/badges/perk.exchange/${{ github.repository_owner }}:${{ github.event.repository.name }}:${{ github.head_ref }}/Donation-Made?cb=1 'Perk Badge')](https://perk.exchange/link/invoice/perk.exchange/${{ github.repository_owner }}:${{ github.event.repository.name }}:${{ github.head_ref }})"
