name: Insert branch name to the PR description

on:
  pull_request:
    types:
      - opened

jobs:
  replace-description:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: PR description replace
        uses: kaskar2008/action-pr-description-replace@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          find: '%BRANCH%'
          replace: ${{ github.head_ref }}
