name: Creates and Updates PR
on:
  push:
    branches:
    - 'releases/**'
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: update-pull-request
      uses: kt3k/update-pr-description@v2
      with:
        pr_body: |
            ## Description

            Please include a summary of the changes and the related issue.

            ## Related URL

            [Your URL here](https://example.com/some-url?pr=${{ github.event.pull_request.number }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
